image: python-node

stages:
  - test
  - build
  - deploy

variables:
  # name it 'flask_deployment-commit-<commit-hash>'
  DEPLOYMENT_CONTAINER: "flask_deployment-commit-${CI_COMMIT_SHA}"

#build_react_app:
#  stage: build
#  script:
#    - cd client/lampenhaus
#    - npm i
#    - npm run build
#
#test_flask_api:
#  stage: test
#  script:
#    - pip install -r requirements-dev.txt
#    - pytest

# services:
#   - docker:dind

deploy_flask_app:
  image: python-node-docker
  stage: deploy
  script:
    # logging
    - docker info
    - docker ps
    - docker ps -a
    - docker images
    # stop and remove old deployment container containing the string 'flask_deployment' if it exists
    # || true makes sure that the job doesn't fail if there is no deployment container currently up and running
    - docker rm $(docker stop $(docker ps | grep "flask_deployment" | awk '{print $1}')) || true
    # run new deployment container in detached mode with port mapping
    - docker run -d -it --name $DEPLOYMENT_CONTAINER -p 5000:5000 python-node /bin/sh
    # run simple http server inside flask_deployment for test purposes
    # - docker exec -d flask_deployment mkdir webpage
    # - docker exec -i flask_deployment bash -c "cd webpage && echo 'hello3 world' >> index.html"
    # - docker exec -d flask_deployment bash -c "cd webpage && python -m http.server"
    - docker cp ../frontend $DEPLOYMENT_CONTAINER:/frontend
    - docker exec -d $DEPLOYMENT_CONTAINER bash -c "cd frontend && . deploy_flask_app.sh"
