stages:
  - test
  - build
  - deploy

test_react-app:
  image: node_alpine
  stage: test
  script:
    - cd client/lampenhaus
    - npm i
    - npm run build
    - npm test

build_react_app:
  image: node_alpine
  stage: build
  script:
    - cd client/lampenhaus
    - npm i
    - npm run build

test_flask_api:
  image: jfloff/alpine-python:3.4
  stage: test
  script:
    - pip install -r requirements-dev.txt
    - pytest