image: python-node

stages:
  - test
  - build
  - deploy

#build_react_app:
#  stage: build
#  script:
#    - cd client/lampenhaus
#    - npm i
#    - npm run build
#
#test_flask_api:
#  stage: test
#  script:
#    - pip install -r requirements-dev.txt
#    - pytest

# services:
#   - docker:dind

deploy_flask_app:
  image: python-node-docker
  stage: deploy
  script:
    # logging
    - docker info
    - docker ps -a
    - docker images
    # stop and remove old deployment container
    - docker stop flask_deployment || true
    - docker rm flask_deployment || true
    # run deployment container in detached mode and name it 'flask_deployment'
    - docker run -d -it --name flask_deployment -p 5000:5000 python-node /bin/sh
    # run simple http server inside flask_deployment for test purposes
    # - docker exec -d flask_deployment mkdir webpage
    # - docker exec -i flask_deployment bash -c "cd webpage && echo 'hello3 world' >> index.html"
    # - docker exec -d flask_deployment bash -c "cd webpage && python -m http.server"
    - docker cp ../frontend flask_deployment:/frontend
    - docker exec -it flask_deployment bash -c "cd frontend && ./deploy_flask_app.sh"
