image: python-node

stages:
  - test
  - build
  - deploy

build_react_app:
  stage: build
  script:
    - cd client/lampenhaus
    - npm i
    - npm run build

test_flask_api:
  stage: test
  script:
    - pip install -r requirements-dev.txt
    - pytest
